import React, { useState } from "react";
import { Header } from "../components/Header";
import { useAuth } from "../context/AuthContext";
import { API_BASE_URL } from "../services/api";
import {
  FileText, Download, Loader2, Sparkles, Check, CheckCircle2,
  ShieldAlert
} from "lucide-react";

export const ReportsPage: React.FC = () => {
  const { user } = useAuth();
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const handleDownloadPdf = async () => {
    setDownloading(true);
    setError("");
    setSuccess("");
    try {
      const response = await fetch(`${API_BASE_URL}/api/reports/download-pdf`, {
        headers: {
          "Authorization": `Bearer ${localStorage.getItem("access_token")}`
        }
      });
      if (!response.ok) {
        throw new Error("Failed to compile financial PDF report");
      }
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `financial_report_${user?.full_name.toLowerCase().replace(" ", "_") || "user"}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setSuccess("Your financial report downloaded successfully!");
      setTimeout(() => setSuccess(""), 4000);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to download report. Ensure uvicorn server is online.");
      setTimeout(() => setError(""), 4000);
    } finally {
      setDownloading(false);
    }
  };

  const reportModules = [
    { title: "Financial Summary", desc: "Aggregated monthly cash inflows, category outflows, and net savings metrics." },
    { title: "ML Risk Analysis", desc: "Machine learning assessment of your risk level (Low/Medium/High) and safety ratings." },
    { title: "Health Score Card", desc: "Breakdown of savings rates, debt ratio, budget discipline, and final health index." },
    { title: "Personalized AI Advisory", desc: "Custom strategic action plan generated by Gemini AI covering spending and investments." }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col relative pb-16">
      <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] rounded-full bg-emerald-500/5 blur-[120px] pointer-events-none" />
      
      <Header />

      <main className="max-w-4xl mx-auto w-full px-6 md:px-12 pt-8 flex-1 flex flex-col gap-8 relative z-10">
        <div className="flex flex-col gap-1.5">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-emerald-400" />
            <h1 className="text-2xl font-black text-white">Financial Statement Reports</h1>
          </div>
          <p className="text-xs text-slate-400">
            Generate and export institutional-grade PDF summary statements compiled with AI recommendations.
          </p>
        </div>

        {error && (
          <div className="p-4 rounded-2xl bg-red-500/10 border border-red-500/30 text-red-400 text-xs font-semibold flex items-center gap-2 animate-pulse">
            <ShieldAlert className="w-4.5 h-4.5" /> {error}
          </div>
        )}
        {success && (
          <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold flex items-center gap-2">
            <Check className="w-4.5 h-4.5" /> {success}
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Action Card */}
          <div className="glass-panel p-6 rounded-3xl border border-white/5 md:col-span-1 flex flex-col justify-between h-80">
            <div className="space-y-3">
              <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Export Document</span>
              <h3 className="text-lg font-black text-white leading-tight">Monthly FinRisk Statement</h3>
              <p className="text-xs text-slate-400 leading-normal">
                Includes all transactional logs, charts, health indicators, and expert AI reviews.
              </p>
            </div>

            <button
              onClick={handleDownloadPdf}
              disabled={downloading}
              className="w-full py-3.5 bg-emerald-500/20 hover:bg-emerald-500/30 border border-emerald-500/30 hover:border-emerald-500/40 text-emerald-400 text-xs font-semibold rounded-2xl transition-all flex items-center justify-center gap-2"
            >
              {downloading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" /> Compiling...
                </>
              ) : (
                <>
                  <Download className="w-4.5 h-4.5" /> Generate PDF Report
                </>
              )}
            </button>
          </div>

          {/* Details list */}
          <div className="glass-panel p-6 rounded-3xl border border-white/5 md:col-span-2 flex flex-col gap-5">
            <div className="flex justify-between items-center pb-2 border-b border-white/5">
              <span className="text-xs text-white font-bold uppercase tracking-wider">Report Structure Modules</span>
              <Sparkles className="w-4.5 h-4.5 text-emerald-400" />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {reportModules.map((m, idx) => (
                <div key={idx} className="p-4 rounded-2xl border border-white/5 bg-slate-900/40 space-y-1.5">
                  <div className="flex items-center gap-1.5 text-emerald-400 text-xs font-bold uppercase tracking-wider">
                    <CheckCircle2 className="w-3.5 h-3.5" /> {m.title}
                  </div>
                  <p className="text-[10px] text-slate-400 leading-relaxed">{m.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};
export default ReportsPage;
